#!/usr/bin/env python3
"""
Explanation of how service_list_entry is generated in OrderCreate payload.
This shows the complete flow from ServiceListRS to DataLists.ServiceList in OrderCreateRQ.
"""

def explain_service_list_generation():
    """Explain how service_list_entry is generated in OrderCreate payload."""
    print("=" * 80)
    print("HOW SERVICE_LIST_ENTRY IS GENERATED IN ORDERCREATE")
    print("=" * 80)
    
    print("📋 STEP-BY-STEP PROCESS:")
    print()
    
    print("1️⃣ **Source Data**: ServiceListRS.Services.Service")
    print("   - Input: ServiceListRS response from API")
    print("   - Contains: Service details, pricing, associations, etc.")
    print()
    
    print("2️⃣ **Service Selection**: Filter selected services")
    print("   - Check if service.ObjectKey is in selected_services list")
    print("   - Only process services that user has selected")
    print()
    
    print("3️⃣ **Service List Entry Creation**:")
    print("   ```python")
    print("   service_list_entry = {")
    print("       'ObjectKey': service_key,                    # From ServiceListRS")
    print("       'ServiceID': service.get('ServiceID', {}),  # ServiceID from ServiceListRS")
    print("       'Name': service.get('Name', {}),            # Service name")
    print("       'Descriptions': service.get('Descriptions', {}),  # Service descriptions")
    print("       'Price': service.get('Price', []),         # Service pricing")
    print("       'BookingInstructions': service.get('BookingInstructions', {}),")
    print("       'ServiceDefinitionRef': service.get('ServiceDefinitionRef', {}),")
    print("       'Associations': service.get('Associations', []),  # Traveler/Flight associations")
    print("       'PricedInd': service.get('PricedInd', True)  # Pricing indicator")
    print("   }")
    print("   ```")
    print()
    
    print("4️⃣ **DataLists.ServiceList Population**:")
    print("   ```python")
    print("   add_to_service_list(order_create_rq['Query']['DataLists']['ServiceList']['Service'], service_list_entry)")
    print("   ```")
    print()
    
    print("5️⃣ **add_to_service_list Function**:")
    print("   ```python")
    print("   def add_to_service_list(service_list: List[Dict[str, Any]], service_data: Dict[str, Any]) -> None:")
    print("       '''Add service to DataLists.ServiceList with validation - DRY principle'''")
    print("       if service_data and service_data.get('ObjectKey'):")
    print("           service_list.append(service_data)")
    print("   ```")
    print()
    
    print("📊 **FINAL RESULT**:")
    print("   - DataLists.ServiceList.Service[] contains all selected services")
    print("   - Each service has complete details from ServiceListRS")
    print("   - Used for OrderCreateRQ per NDC specification")
    print()
    
    print("🔍 **KEY FIELDS MAPPED**:")
    print("   - ObjectKey: Service identifier (e.g., '1-ServiceIdAF-13')")
    print("   - ServiceID: Service ID with Owner (e.g., 'SRV13', Owner: 'AF')")
    print("   - Name: Service name (e.g., 'BAG:LUGGAGE-FIRST ADDITIONAL BAG')")
    print("   - Descriptions: Service descriptions")
    print("   - Price: Service pricing information")
    print("   - Associations: Traveler and flight associations")
    print("   - PricedInd: Whether service requires pricing (true/false)")
    print()
    
    print("🎯 **PURPOSE**:")
    print("   - Provides complete service details in OrderCreateRQ")
    print("   - Enables airline to process the service request")
    print("   - Maintains service associations with travelers and flights")
    print("   - Follows NDC specification for service data")

def show_example_mapping():
    """Show example of how ServiceListRS maps to DataLists.ServiceList."""
    print("\n" + "=" * 80)
    print("EXAMPLE MAPPING: ServiceListRS → DataLists.ServiceList")
    print("=" * 80)
    
    print("📥 **INPUT (ServiceListRS.Services.Service)**:")
    print("```json")
    print("{")
    print('  "ObjectKey": "1-ServiceIdAF-13",')
    print('  "ServiceID": {')
    print('    "ObjectKey": "c5a33bf8-a8c7-4123-a33b-f8a8c771000d",')
    print('    "value": "SRV13",')
    print('    "Owner": "AF"')
    print('  },')
    print('  "Name": {')
    print('    "value": "BAG:LUGGAGE-FIRST ADDITIONAL BAG"')
    print('  },')
    print('  "Descriptions": { ... },')
    print('  "Price": [ ... ],')
    print('  "Associations": [ ... ],')
    print('  "PricedInd": false')
    print("}")
    print("```")
    print()
    
    print("📤 **OUTPUT (DataLists.ServiceList.Service)**:")
    print("```json")
    print("{")
    print('  "ObjectKey": "1-ServiceIdAF-13",')
    print('  "ServiceID": {')
    print('    "ObjectKey": "c5a33bf8-a8c7-4123-a33b-f8a8c771000d",')
    print('    "value": "SRV13",')
    print('    "Owner": "AF"')
    print('  },')
    print('  "Name": {')
    print('    "value": "BAG:LUGGAGE-FIRST ADDITIONAL BAG"')
    print('  },')
    print('  "Descriptions": { ... },')
    print('  "Price": [ ... ],')
    print('  "BookingInstructions": { ... },')
    print('  "ServiceDefinitionRef": { ... },')
    print('  "Associations": [ ... ],')
    print('  "PricedInd": false')
    print("}")
    print("```")
    print()
    
    print("🔄 **TRANSFORMATION**:")
    print("   - Direct mapping: Most fields are copied as-is")
    print("   - Added fields: BookingInstructions, ServiceDefinitionRef")
    print("   - Preserved: ObjectKey, ServiceID, Name, Descriptions, Price, Associations, PricedInd")
    print("   - Purpose: Complete service details for OrderCreate processing")

def main():
    """Main explanation function."""
    explain_service_list_generation()
    show_example_mapping()
    
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print("✅ The service_list_entry is generated by:")
    print("   1. Extracting service data from ServiceListRS")
    print("   2. Creating a structured entry with all required fields")
    print("   3. Adding it to DataLists.ServiceList in OrderCreateRQ")
    print("   4. Following NDC specification for service data")
    print()
    print("🎯 This ensures complete service information is available")
    print("   for the airline to process the OrderCreate request.")

if __name__ == "__main__":
    main()
