#!/usr/bin/env python3
"""
Complete test to show the payloads generated by our PricedInd=false implementation.
This demonstrates the complete workflow from detection to OrderCreate.
"""

import json
import sys
import os
from typing import Dict, Any, List

# Add the scripts directory to the path
sys.path.append(os.path.join(os.path.dirname(__file__), 'scripts'))

from build_flightprice_ancillary_rq import (
    build_flightprice_ancillary_request,
    detect_pricing_required
)
from build_ordercreate_rq import generate_order_create_rq

def load_real_workflow_data():
    """Load real workflow data."""
    try:
        workflow_dir = "Shopping and booking with Seat and Ancillary where both of them requires pricing"
        
        # Load responses
        with open(f'{workflow_dir}/4_FlightPriceRS.json', 'r') as f:
            initial_flight_price = json.load(f)
        
        with open(f'{workflow_dir}/6_ServiceListRS.json', 'r') as f:
            servicelist_response = json.load(f)
        
        with open(f'{workflow_dir}/8_SeatAvailabilityRS.json', 'r') as f:
            seatavailability_response = json.load(f)
        
        with open(f'{workflow_dir}/10_FlightPriceRS.json', 'r') as f:
            final_flight_price = json.load(f)
        
        return {
            'initial_flight_price': initial_flight_price,
            'servicelist_response': servicelist_response,
            'seatavailability_response': seatavailability_response,
            'final_flight_price': final_flight_price
        }
    
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

def demonstrate_complete_workflow():
    """Demonstrate the complete PricedInd=false workflow."""
    print("🚀 COMPLETE PRICEDIND=FALSE WORKFLOW DEMONSTRATION")
    print("=" * 80)
    
    # Load data
    data = load_real_workflow_data()
    if not data:
        print("❌ Failed to load data")
        return
    
    print("✅ Loaded real workflow data")
    
    # Step 1: Analyze PricedInd status
    print("\n" + "=" * 60)
    print("STEP 1: ANALYZING PRICEDIND STATUS")
    print("=" * 60)
    
    # Find services with PricedInd=false
    services = data['servicelist_response'].get('Services', {}).get('Service', [])
    priced_false_services = [s for s in services if not s.get('PricedInd', True)]
    
    # Find seats with PricedInd=false
    seat_services = data['seatavailability_response'].get('Services', {}).get('Service', [])
    priced_false_seats = [s for s in seat_services if not s.get('PricedInd', True)]
    
    print(f"📋 Found {len(priced_false_services)} services with PricedInd=false")
    for service in priced_false_services[:3]:  # Show first 3
        print(f"  - {service.get('ObjectKey', 'N/A')}: {service.get('Name', {}).get('value', 'Unknown')}")
    
    print(f"🪑 Found {len(priced_false_seats)} seats with PricedInd=false")
    for seat in priced_false_seats[:3]:  # Show first 3
        print(f"  - {seat.get('ObjectKey', 'N/A')}: {seat.get('Name', {}).get('value', 'Unknown')}")
    
    # Step 2: Test pricing detection
    print("\n" + "=" * 60)
    print("STEP 2: TESTING PRICING DETECTION")
    print("=" * 60)
    
    # Select some items for testing
    selected_services = [s.get('ObjectKey') for s in priced_false_services[:2]]
    selected_seats = [s.get('ObjectKey') for s in priced_false_seats[:1]]
    
    print(f"Selected services: {selected_services}")
    print(f"Selected seats: {selected_seats}")
    
    pricing_info = detect_pricing_required(
        servicelist_response=data['servicelist_response'],
        seatavailability_response=data['seatavailability_response'],
        selected_services=selected_services,
        selected_seats=selected_seats
    )
    
    print(f"\n🔍 Pricing Detection Results:")
    print(f"  Requires pricing: {pricing_info['requires_pricing']}")
    print(f"  Services requiring pricing: {pricing_info['services_require_pricing']}")
    print(f"  Seats requiring pricing: {pricing_info['seats_require_pricing']}")
    
    # Step 3: Generate ancillary pricing request
    print("\n" + "=" * 60)
    print("STEP 3: GENERATING ANCILLARY PRICING REQUEST")
    print("=" * 60)
    
    try:
        ancillary_request = build_flightprice_ancillary_request(
            flight_price_response=data['initial_flight_price'],
            servicelist_response=data['servicelist_response'],
            seatavailability_response=data['seatavailability_response'],
            selected_services=selected_services,
            selected_seats=selected_seats
        )
        
        print("✅ Successfully generated ancillary pricing request!")
        
        # Show request structure
        print(f"\n📊 Generated Request Structure:")
        print(f"  Travelers: {len(ancillary_request.get('Travelers', {}).get('Traveler', []))}")
        print(f"  OriginDestinations: {len(ancillary_request.get('Query', {}).get('OriginDestination', []))}")
        
        # Show offer items
        offers = ancillary_request.get('Query', {}).get('Offers', {}).get('Offer', [])
        if offers:
            offer_items = offers[0].get('OfferItemIDs', {}).get('OfferItemID', [])
            print(f"  Offer Items: {len(offer_items)}")
            
            # Show service items
            service_items = [item for item in offer_items if 'SelectedSeat' not in item]
            print(f"    Service Items: {len(service_items)}")
            for item in service_items:
                print(f"      - {item['value']} (Quantity: {item.get('Quantity', 1)})")
            
            # Show seat items with dynamic data
            seat_items = [item for item in offer_items if 'SelectedSeat' in item]
            print(f"    Seat Items: {len(seat_items)}")
            for item in seat_items:
                print(f"      - {item['value']}")
                if 'SelectedSeat' in item and item['SelectedSeat']:
                    selected_seat = item['SelectedSeat'][0]
                    location = selected_seat.get('Location', {})
                    row = location.get('Row', {}).get('Number', {}).get('value', 'N/A')
                    column = location.get('Column', 'N/A')
                    print(f"        Location: Row {row}, Column {column}")
                    
                    characteristics = location.get('Characteristics', {}).get('Characteristic', [])
                    if characteristics:
                        codes = [char.get('Code', '') for char in characteristics if char.get('Code')]
                        print(f"        Characteristics: {codes}")
        
        # Save the generated request for inspection
        with open('generated_ancillary_pricing_request.json', 'w') as f:
            json.dump(ancillary_request, f, indent=2)
        print(f"\n💾 Saved generated request to: generated_ancillary_pricing_request.json")
        
    except Exception as e:
        print(f"❌ Error generating ancillary pricing request: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Step 4: Generate OrderCreate request
    print("\n" + "=" * 60)
    print("STEP 4: GENERATING ORDERCREATE REQUEST")
    print("=" * 60)
    
    # Create test passenger and payment data
    passengers_data = [{
        "ObjectKey": "PAX1",
        "PTC": "ADT",
        "Name": {
            "Surname": "DOE",
            "Given": ["JON"],
            "Title": "Mr"
        },
        "Gender": "Male",
        "BirthDate": "1990-01-01",
        "Contacts": {
            "AddressContact": {
                "Street": ["123 Main St"],
                "CityName": "Test City",
                "CountrySubDivisionCode": "TS",
                "PostalCode": "12345",
                "CountryCode": {"value": "US"}
            },
            "EmailContact": {
                "Address": {"value": "test@example.com"}
            },
            "PhoneContact": {
                "Application": "Home",
                "Number": [{
                    "value": "1234567890",
                    "CountryCode": "1"
                }]
            }
        },
        "Documents": [{
            "Type": "P",
            "ID": "A1234567",
            "DateOfExpiration": "2030-01-01",
            "CountryOfIssuance": "US"
        }]
    }]
    
    payment_data = {"MethodType": "Cash"}
    
    try:
        order_create_rq = generate_order_create_rq(
            flight_price_response=data['final_flight_price'],
            passengers_data=passengers_data,
            payment_input_info=payment_data,
            servicelist_response=data['servicelist_response'],
            seatavailability_response=data['seatavailability_response'],
            selected_services=selected_services,
            selected_seats=selected_seats
        )
        
        print("✅ Successfully generated OrderCreate request!")
        
        # Show OrderCreate structure
        print(f"\n📊 Generated OrderCreate Structure:")
        query = order_create_rq.get('Query', {})
        
        # Passengers
        passengers = query.get('Passengers', {}).get('Passenger', [])
        print(f"  Passengers: {len(passengers)}")
        
        # OrderItems
        order_items = query.get('OrderItems', {})
        shopping_response = order_items.get('ShoppingResponse', {})
        offers = shopping_response.get('Offers', {}).get('Offer', [])
        if offers:
            offer_items = offers[0].get('OfferItems', {}).get('OfferItem', [])
            print(f"  Shopping Response Offer Items: {len(offer_items)}")
        
        # Additional OfferItems
        additional_offer_items = order_items.get('OfferItem', [])
        print(f"  Additional Offer Items: {len(additional_offer_items)}")
        
        # DataLists
        data_lists = query.get('DataLists', {})
        service_list = data_lists.get('ServiceList', {}).get('Service', [])
        print(f"  ServiceList entries: {len(service_list)}")
        
        # Show service details
        print(f"\n📋 Generated Service List:")
        for service in service_list:
            object_key = service.get('ObjectKey', '')
            name = service.get('Name', {}).get('value', 'Unknown')
            priced_ind = service.get('PricedInd', True)
            print(f"  - {object_key}: {name} (PricedInd: {priced_ind})")
        
        # Show seat details
        print(f"\n🪑 Generated Seat Items:")
        for item in additional_offer_items:
            offer_item_type = item.get('OfferItemType', {})
            if 'SeatItem' in offer_item_type:
                offer_item_id = item.get('OfferItemID', {})
                object_key = offer_item_id.get('value', '')
                seat_item = offer_item_type['SeatItem'][0]
                location = seat_item.get('Location', {})
                if location:
                    row = location.get('Row', {}).get('Number', {}).get('value', 'N/A')
                    column = location.get('Column', 'N/A')
                    print(f"  - {object_key}: Row {row}, Column {column}")
        
        # Save the generated OrderCreate request
        with open('generated_ordercreate_request.json', 'w') as f:
            json.dump(order_create_rq, f, indent=2)
        print(f"\n💾 Saved generated OrderCreate to: generated_ordercreate_request.json")
        
    except Exception as e:
        print(f"❌ Error generating OrderCreate request: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Final summary
    print("\n" + "=" * 80)
    print("🎉 COMPLETE WORKFLOW SUCCESS!")
    print("=" * 80)
    print("✅ PricedInd=false detection: WORKING")
    print("✅ Dynamic seat data extraction: WORKING")
    print("✅ Ancillary pricing request generation: WORKING")
    print("✅ OrderCreate request generation: WORKING")
    print("\n🚀 The complete PricedInd=false workflow is fully functional!")

if __name__ == "__main__":
    demonstrate_complete_workflow()
